### ISSUE TITLE
修改pod子网段失败

### ISSUE THREAD

**Issue by currycan** [fanux/sealos#142]
你好！
       如何修改pod子网段？参看文档，我修改了`kubeadm-config.yaml.tmpl `配置，只修改了`podSubnet`为B类地址私有网段（雪花算法sonyflake会检验是否为私有网段，原有100.64.0.0/10报错），如下：
```yaml
apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterConfiguration
kubernetesVersion: {{.Version}}
controlPlaneEndpoint: "apiserver.cluster.local:6443"
networking:
  podSubnet: 172.16.0.0/20
apiServer:
        certSANs:
        - sealyun.com # this is what I added
        - 127.0.0.1
        - apiserver.cluster.local
        {{range .Masters -}}
        - {{.}}
        {{end -}}
        - {{.VIP}}
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
mode: "ipvs"
ipvs:
        excludeCIDRs: 
        - "{{.VIP}}/32"
```
安装命令：
```shell
sealos init --kubeadm-config kubeadm-config.yaml.tmpl \
    --master 10.177.92.1 \
    --master 10.177.92.2 \
    --master 10.177.92.3 \
    --node 10.177.92.4 \
    --node 10.177.92.5 \
    --node 10.177.92.6 \
    --vip  10.103.97.2 \
    --user root \
    --pk  /root/.ssh/id_ed25519 \
    --version v1.16.0 \
    --pkg-url /kube1.16.0.tar.gz 
```
安装后pod网段并没有修改，查看`kube/conf/kubeadm.yaml`下的`podSubnet`字段值还是`100.64.0.0/10`，请问哪里配置不对吗？谢谢！

**Comment by fanux** [comment]
calico.yaml需要和这个配置一致，可以考虑重装下calico

**Comment by currycan** [comment]
> calico.yaml 需要和这个配置一致，可以考虑重装下 calico
@fanux 你好！意思是直接修改`kubeadm-config.yaml.tmpl`没用吗？另外，我觉得不应该是修改`calico.yaml`，`kubeadm int` 命令里是可以通过`--pod-network-cidr`设定的，我在`kube/shell/master.sh`看到了`kubeadm init --config ../conf/kubeadm.yaml`，其实还是要修改`kubeadm.yaml`，或者直接改这个命令就行。

**Comment by fanux** [comment]
kubeadm是不负责帮你安装CNI的，CNI的参数需要与之一致，CNI的配置参数属于calico的参数

**Comment by currycan** [comment]
@fanux  恩，谢谢！已解决

**Comment by currycan** [comment]
@fanux  您好！
建议这里的podSubnet字段也设置成一个变量值去渲染，如下：
```yaml
apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterConfiguration
kubernetesVersion: {{.Version}}
controlPlaneEndpoint: "apiserver.cluster.local:6443"
networking:
  podSubnet: {{.podSubnet}}
apiServer:
        certSANs:
        - sealyun.com # this is what I added
        - 127.0.0.1
        - apiserver.cluster.local
        {{range .Masters -}}
        - {{.}}
        {{end -}}
        - {{.VIP}}
```
安装命令
```bash
sealos init --master 192.168.0.2 \
    --master 192.168.0.3 \
    --master 192.168.0.4 \
    --node 192.168.0.5 \
    --user root \
    --passwd your-server-password \
    --version v1.14.1 \
    --podsubnet 172.16.0.0/20 \
    --pkg-url /root/kube1.14.1.tar.gz  
````
其中加入了pod子网的定制。谢谢！
