### ISSUE TITLE
staicpod yaml文件未生成

### ISSUE THREAD

**Issue by fanux** [fanux/sealos#262]
```
/etc/kubernetes/manifests/kube-sealyun-lvscare.yaml: No such file or directory
```
离线包版本 1.18.0
sealos版本 v3.2.0-beta.2

原因：node节点manifests目录不存在，需要先创建改目录再cat yaml > staticpod.yaml

**Comment by fanux** [comment]
https://github.com/fanux/sealos/blob/develop/install/join.go#L129   join时要确保目录存在
https://github.com/fanux/sealos/blob/develop/install/join.go#L111  同理

**Comment by sealrobot** [comment]
完成这个issue中的任务，代码成功合并，fanux 老板就会支付你 13 元, 
请在issue中回复:
/alipay [你的支付宝号] （如 /alipay 15281817171）
以让我知道您的支付宝

/apply
如上apply指令表示申请任务，第一个申请人将被分配任务，如果任务已经被分配请不要重复申请

**Comment by sealrobot** [comment]
@jinnzy 你成功申请了任务，任务完成后使用/alipay xxx 提供支付宝号

**Comment by fanux** [comment]
测试验证方法：

1. 起一个3 master 1 node的集群
2. 安装完成后 node上 /etc/kuberentes/manifests/ 下面会生成 static pod yaml 把内容回复在issue中
3. 使用ipvsadm -Ln命令查看ipvs规则是否正常
4. 在master0上使用sealos clean --master x.x.x.x删除一个master
5. 再去到node上用2，3步骤检验 配置文件与ipvs规则是否正常

**Comment by jinnzy** [comment]
```
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    component: kube-sealyun-lvscare
    tier: control-plane
  name: kube-sealyun-lvscare
  namespace: kube-system
spec:
  containers:
  - args:
    - care
    - --vs
    - 10.103.97.2:6443
    - --health-path
    - /healthz
    - --health-schem
    - https
    - --rs
    - 172.16.9.176:6443
    - --rs
    - 172.16.9.177:6443
    - --rs
    - 172.16.9.178:6443
    command:
    - /usr/bin/lvscare
    image: fanux/lvscare:latest
    imagePullPolicy: IfNotPresent
    name: kube-sealyun-lvscare
    resources: {}
    securityContext:
      privileged: true
  hostNetwork: true
  priorityClassName: system-cluster-critical
status: {}
```

**Comment by jinnzy** [comment]
```
[root@iZ2ze098qx0mboinwrt47qZ kube]# cat /etc/kubernetes/manifests/kube-sealyun-lvscare.yaml 
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    component: kube-sealyun-lvscare
    tier: control-plane
  name: kube-sealyun-lvscare
  namespace: kube-system
spec:
  containers:
  - args:
    - care
    - --vs
    - 10.103.97.2:6443
    - --health-path
    - /healthz
    - --health-schem
    - https
    - --rs
    - 172.16.9.176:6443
    - --rs
    - 172.16.9.177:6443
    command:
    - /usr/bin/lvscare
    image: fanux/lvscare:latest
    imagePullPolicy: IfNotPresent
    name: kube-sealyun-lvscare
    resources: {}
    securityContext:
      privileged: true
  hostNetwork: true
  priorityClassName: system-cluster-critical
status: {}
```
