### ISSUE TITLE
多IP时yaml文件渲染错误

### ISSUE THREAD

**Issue by fanux** [fanux/sealos#264]
```
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    component: kube-sealyun-lvscare
    tier: control-plane
  name: kube-sealyun-lvscare
  namespace: kube-system
spec:
  containers:
  - args:
    - care
    - --vs
    - 10.103.97.2:6443
    - --health-path
    - /healthz
    - --health-schem
    - https
    - --rs
    - 172.16.9.176-172.16.9.178:6443
    command:
    - /usr/bin/lvscare
    image: fanux/lvscare:latest
    imagePullPolicy: IfNotPresent
    name: kube-sealyun-lvscare
    resources: {}
    securityContext:
      privileged: true
  hostNetwork: true
  priorityClassName: system-cluster-critical
status: {}
```

渲染成了  172.16.9.176-172.16.9.178:6443
使用 sealos init --master 172.16.9.176-172.16.9.178
