### ISSUE TITLE
lvscare需要挂载/lib/modules

### ISSUE THREAD

**Issue by fanux** [fanux/sealos#312]
不挂载的话这个命令退出码会始终是1导致初始化问题。
```
		if out, err := exec.Command("modprobe", "-va", "ip_vs").CombinedOutput(); err != nil {
			fmt.Printf("Running modprobe ip_vs failed with message: `%s`, error: %v\n", strings.TrimSpace(string(out)), err)
		}
```
static pod yaml参考kube-proxy:
```
    volumeMounts:
    - mountPath: /lib/modules
      name: lib-modules
      readOnly: true
  volumes:
  - hostPath:
      path: /lib/modules
      type: ""
    name: lib-modules
```
PS：增加lvscare镜像版本参数
