### ISSUE TITLE
老版本升级lvscare修复bug

### ISSUE THREAD

**Issue by fanux** [fanux/sealos#315]
问题描述：
   lvscare引入了k8s的一个库，而该库有bug,使用如下步骤进行修复，否则会产生大量error日志（不影响功能）且开机重启不能正常下发ipvs规则。

修复：
1. 在所有node节点更新lvscare镜像  docker pull fanux/lvscare
2. 修改node节点static pod yaml 在/etc/kubernetes/manifests下，增加/lib/module文件挂载：
```
    volumeMounts:
    - mountPath: /lib/modules
      name: lib-modules
      readOnly: true
  volumes:
  - hostPath:
      path: /lib/modules
      type: ""
    name: lib-modules
```
