### ISSUE TITLE
support auto config hostname

### ISSUE THREAD

**Issue by willzhang** [fanux/sealos#501]
每次部署要逐个节点手动配置所有主机名，违背丝滑宗旨，但是sealos init --hostname 传递参数过多也不够优雅。

是否可以考虑sealos init支持从配置文件部署集群？一方面部署的配置持久化，另一方面可以方便定义大量自定义参数：

```
sealos --generate example-cluster.yaml

sealos init \
  --config example-cluster.yaml \
  --override-hostname=true
```

**Comment by oldthreefeng** [comment]
一直支持从配置文件安装的。 
--config

**Comment by oldthreefeng** [comment]
@willzhang  https://github.com/oldthreefeng/sealos/tree/sethostname  我没准备提pr... 感觉这样乖乖的.

**Comment by willzhang** [comment]
那是k8s的配置文件

**Comment by willzhang** [comment]
像这样
```
sealos create config

or
sealos create config --with-kubernetes v1.19.2 -f /root/config-sample.yaml
```
修改配置文件

```
# vim /root/config-sample.yaml

[hosts]
hostname: master1, address: 192.168.1.1, user: root, password: 123456
hostname: master2, address: 192.168.1.2, user: root, password: 123456
hostname: master3, address: 192.168.1.3, user: root, password: 123456

hostname: node1, address: 192.168.1.1, user: root, password: 123456
hostname: node2, address: 192.168.1.2, user: root, password: 123456
hostname: node3, address: 192.168.1.3, user: root, password: 123456

[master]
master1
master2
master3

[etcd]
master1
master2
master3

[node]
node1
node2
node3

[env]
pkg-url: /root/kube1.19.2.tar.gz
kubernetes_version: v1.19.2
clusterName: cluster1
network_plugin: calico
controlPlaneEndpoint: apiserver.cluster.local.
registry_mirror: mirror.aliyun.com
insecureRegistries: 192.168.1.100
```


参考：https://github.com/kubesphere/kubekey
```
apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Cluster
metadata:
  name: sample
spec:
  hosts:
  - {name: node1, address: 192.168.1.110, internalAddress: 192.168.1.110, user: root, password: 123456}
  - {name: node2, address: 192.168.1.111, internalAddress: 192.168.1.111, user: root, password: 123456}
  - {name: node3, address: 192.168.1.112, internalAddress: 192.168.1.112, user: root, password: 123456}
  - {name: node4, address: 192.168.1.113, internalAddress: 192.168.1.113, user: root, password: 123456}
  roleGroups:
    etcd:
    - node1
    - node2
    - node3
    master: 
    - node1
    - node2
    - node3
    worker:
    - node4
  controlPlaneEndpoint:
    domain: lb.kubesphere.local
    address: ""
    port: "6443"
  kubernetes:
    version: v1.17.9
    imageRepo: kubesphere
    clusterName: cluster.local
  network:
    plugin: calico
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
  registry:
    registryMirrors: []
    insecureRegistries: []
  addons: []
```
