### ISSUE TITLE
修改~/.sealos/config.yaml中的配置项， 导致panic: runtime error:index out of range [0] with length 0

### ISSUE THREAD

**Issue by fufengyuan** [fanux/sealos#520]
**哪个命令或者组件**
```
sealos join --master 172.31.25.40
```
**描述这个缺陷**
操作步骤
```
sealos init --passwd '' \
--master 172.31.25.38  --master 172.31.25.39 --master 172.31.25.40  \
--pkg-url /root/kube1.19.3.tar.gz \
	--version v1.19.3
```
在172.31.25.38上使用以上命令安装成功，集群可以正常运行。
然后修改了每个节点的docker镜像地址，分别重启docker后发现master 172.31.25.40启动异常，
然后就在172.31.25.38上使用`sealos clean --master 172.31.25.40`命令清理掉异常节点，再使用`sealos join --master 172.31.25.40`就报错。

**重现步骤（如果有需要可以附加图片）**
1. 
清理节点`sealos clean --master 172.31.25.40`
![image](https://user-images.githubusercontent.com/31567513/98627111-60008480-234e-11eb-93ed-ab5d6593e7ce.png)

2.加入节点
`sealos join --master 172.31.25.40`
![image](https://user-images.githubusercontent.com/31567513/98627187-8d4d3280-234e-11eb-87d5-b0d5fa8750b6.png)

**测试结果**
1. panic: runtime error:index out of range [0] with length 0

**期望结果**
1. 期望出现 加入master成功
   前置条件: 已有两个master正常运行
   操作步骤:
   1. sealos clean --master 172.31.25.40
   2. sealos join --master 172.31.25.40
   预期结果:
   1. 加入成功

**运行环境**

- Docker版本:   1.18.06.3-ce
- Kubernetes版本 : eg.kube1.16.tar.gz
- sealos版本: lastest
- 操作系统:  redhat7.8  内核5.8.3-1.el7.elrepo.x86_64
- 运行模式:  虚拟机 ( virbox, 内存 8gb, cpu 4核 ,存储 100gb ) 
- 集群规模:   eg 3master 0node
- 附加说明: k8s: 1.19.3

**Comment by oldthreefeng** [comment]
清理master看一下wiki里面的清理， 还需要清etcd的节点， 另外这个panic我晚点看能不能重现一下。

**Comment by fufengyuan** [comment]
清理了还是一样的呢

**Comment by fufengyuan** [comment]
> 清理master看一下wiki里面的清理， 还需要清etcd的节点， 另外这个panic我晚点看能不能重现一下。

还是一样的，我试试重新安装整个集群，看看能不能解决

**Comment by zhangguanzhang** [comment]
感觉配置文件导致master0不存在

**Comment by oldthreefeng** [comment]
> panic: runtime error:index out of range [0] with length 0

我复现不出来. 能把错误的完整 join 日志打印出来么?

**Comment by oldthreefeng** [comment]
我这边大概能定位到问题了.  你可能修改了`.sealos/config.yaml` 里面masters相关配置, 比如以下的一个基本配置. 删除masters的列表后, 则会出现 `panic: runtime error:index out of range [0] with length 0`.  
导致了这个错误的发生.
```
masters:
- 192.168.60.128:22
- 192.168.60.129:22
- 192.168.60.130:22
nodes: []
dnsdomain: cluster.local
apiservercertsans:
- 127.0.0.1
- apiserver.cluster.local
- 192.168.60.128
- 192.168.60.129
- 192.168.60.130
- 10.103.97.2
user: root
passwd: ""
privatekey: /root/.ssh/id_rsa
pkpassword: ""
apiserverdomian: apiserver.cluster.local
vip: 10.103.97.2
pkgurl: kube1.19.3.tar.gz
version: v1.19.3
repo: k8s.gcr.io
podcidr: 100.64.0.0/10
svccidr: 10.96.0.0/12
certpath: /root/.sealos/pki
certetcdpath: /root/.sealos/pki/etcd
lvscarename: fanux/lvscare
lvscaretag: latest
alioss:
  ossendpoint: ""
  accesskeyid: ""
  accesskeysecrets: ""
  bucketname: ""
  objectpath: ""
```
