### ISSUE TITLE
join node Use a JoinConfiguration file. not Use cli command

### ISSUE THREAD

**Issue by oldthreefeng** [fanux/sealos#577]
**哪个命令或者组件**
sealos init 
sealos join
**描述这个缺陷**

join node now is like , it lose Define of criSocket (default is docker).  
```
kubeadm join 10.103.97.2:6443 --token 4lyplq.z7qavyo67ayuf0gk --discovery-token-ca-cert-hash sha256:c59a66fb933dacf77d19049665a77a528d3242964acb6fed759460b03e33d9a0 -v 0
```

For join master . it define in  kubeadm-join-config.yaml

```
cat kubeadm-join-config.yaml 
apiVersion: kubeadm.k8s.io/v1beta2	
caCertPath: /etc/kubernetes/pki/ca.crt
discovery:
  bootstrapToken:
    apiServerEndpoint: {{.Master0}}:6443
    token: {{.TokenDiscovery}}
    caCertHashes:
    - {{.TokenDiscoveryCAHash}}
  timeout: 5m0s
kind: JoinConfiguration
controlPlane:
  localAPIEndpoint:
    advertiseAddress: {{.Master}}
    bindPort: 6443
nodeRegistration:
  criSocket: /run/containerd/containerd.sock
```

## solution 1 

```
$ cat kubeadm-join-worker-config.yaml 
apiVersion: kubeadm.k8s.io/v1beta2	
caCertPath: /etc/kubernetes/pki/ca.crt
discovery:
  bootstrapToken:
    apiServerEndpoint: {{.Apiserver}}:6443
    token: {{.TokenDiscovery}}
    caCertHashes:
    - {{.TokenDiscoveryCAHash}}
  timeout: 5m0s
nodeRegistration:
  criSocket: /run/containerd/containerd.sock
```

## solution  2
Use ` --cri-socket ` to define. 

```
kubeadm join 10.103.97.2:6443 --token 4lyplq.z7qavyo67ayuf0gk --discovery-token-ca-cert-hash sha256:c59a66fb933dacf77d19049665a77a528d3242964acb6fed759460b03e33d9a0 -v 0   --cri-socket /run/containerd/containerd.sock
```
> kubeadm: avoid detection of the container runtime for commands that do not need it

xref: https://github.com/kubernetes/kubernetes/pull/97625
