### ISSUE TITLE
sealos不小心将init 的节点服务器给clean后无法再join master 节点 解决

### ISSUE THREAD

**Issue by kuangzaodelatiao-yyy** [fanux/sealos#580]
# sealos不小心将init的节点clean掉后，无法再次添加master 节点的解决方案

我安装的是  三个master 多个node节点的k8s  但是发现  除了第一个init 节点可以 添加master 以及node 外  其他节点都不可以使用sealos去添加这个集群的节点  就此我还差点重装整个集群

解决：

1. 在init 节点的 /root/.sealos  文件发送到其他想要使用sealos 控制的节点（新init 节点）上
2. （新init 节点）vim ~/.sealos/config.yaml  检查 masters   、nodes 、apiservercertsans  是否与当前集群一致
3. （新init 节点）kubectl describe configmap kubeadm-config -n kube-system > kubeadm-config.yaml   
将apiEndpoints 修改 为现有集群的状态
```
ClusterStatus:
----
apiEndpoints:
  dsk8scluster11:
    advertiseAddress: 10.2.1.11
    bindPort: 6443
```
4、在新的init 节点上 的执行 sealos join 命令尝试  
注： 如果出现证书校验异常  建议 将现有集群的master节点 执行
```
mv /root/.sealos/pki  /root/.sealos/pki_bak
cp -r /etc/kubernetes/pki/ /root/.sealos
```
