### ISSUE TITLE
缺陷: init初始化安装k8s出错

### ISSUE THREAD

**Issue by jdxia** [fanux/sealos#791]
**sealos init**

**ubuntu18.04安装1.19出错, 提示让我clean, clean了也不行**

**重现步骤**

ubuntu18.04
sealos init —passwd '123456' \
    —master 192.168.33.151  \
    —node 192.168.33.152 —node 192.168.33.153 \
    —pkg-url /root/kube1.19.16.tar.gz \
    —version v1.19.16

报错信息
09:18:37 [DEBG] [scp.go:337] [ssh][192.168.33.151:22]transfer local [/root/.sealos/pki/sa.pub] to Dst [/etc/kubernetes/pki/sa.pub] total size is: 0.44KB ;speed is 0KB
09:18:37 [INFO] [init.go:131] local /etc/hosts is already exists apiserver.cluster.local
09:18:37 [DEBG] [ssh.go:58] [192.168.33.151:22] grep -qF '192.168.33.151 apiserver.cluster.local' /etc/hosts || echo 192.168.33.151 apiserver.cluster.local >> /etc/hosts
09:18:38 [INFO] [ssh.go:13] [ssh][192.168.33.151:22] kubeadm init --config=/root/kubeadm-config.yaml --upload-certs -v 0
09:18:38 [DEBG] [ssh.go:25] [ssh][192.168.33.151:22]command result is: could not interpret GroupVersionKind; unmarshal error: error converting YAML to JSON: yaml: line 16: mapping values are not allowed in this context
To see the stack trace of this error execute with --v=5 or higher

09:18:38 [EROR] [ssh.go:28] [ssh][192.168.33.151:22]Error exec command failed: Process exited with status 1
09:18:38 [EROR] [init.go:190] [192.168.33.151:22] install kubernetes failed. please clean and uninstall.

**Comment by cuisongliu** [comment]
```
command result is: could not interpret GroupVersionKind; unmarshal error: error converting YAML to JSON: yaml: line 16: mapping values are not allowed in this context
```

检测一下你的 kubeadm-config.yaml

**Comment by oldthreefeng** [comment]
docker没起来， 或者下载的包和自己的系统架构不一样。

**Comment by jdxia** [comment]
![image](https://user-images.githubusercontent.com/23069626/149865206-5edbb717-c5da-47c4-9ed0-230e0e66b9c9.png)
sealos如果不把--port=0去掉
kubectl get cs会显示, 健康检查不过
![image](https://user-images.githubusercontent.com/23069626/149865229-b1f62e3f-f354-49fd-b78d-c06e3f46b854.png)
脚本能否加上这个?
sed -i -e '/--port=0/d' /etc/kubernetes/manifests/kube-controller-manager.yaml

sed -i -e '/--port=0/d' /etc/kubernetes/manifests/kube-scheduler.yaml

**Comment by jdxia** [comment]
我去掉--port=0,之后
![image](https://user-images.githubusercontent.com/23069626/149865306-7eb13581-392e-433f-aea5-a5d10da95cb5.png)

**Comment by jdxia** [comment]
辛苦合并下这个脚本

**Comment by oldthreefeng** [comment]
这个是k8s上游问题，为了安全禁用的。 @jdxia

**Comment by rea1shane** [comment]
我遇到了相同的报错：

```
17:33:04 [INFO] [ssh.go:27] [ssh][172.16.88.37:22] kubeadm init --config=/root/kubeadm-config.yaml --upload-certs -v 0
17:33:04 [DEBG] [ssh.go:39] [ssh][172.16.88.37:22]command result is: could not interpret GroupVersionKind; unmarshal error: error converting YAML to JSON: yaml: line 16: mapping values are not allowed in this context
To see the stack trace of this error execute with --v=5 or higher

17:33:04 [EROR] [ssh.go:42] [ssh][172.16.88.37:22]Error exec command failed: Process exited with status 1
17:33:04 [EROR] [init.go:204] [172.16.88.37:22] install kubernetes failed. please clean and uninstall.
```

查看 `kubeadm-config.yaml` 文件：

```yaml
 14 networking:
 15   # dnsDomain: cluster.local
 16   podSubnet: 1.2.3.4/10
 17   serviceSubnet: 5.6.7.8/12
 18 apiServer:
```

`sealos clean` 后重试依旧出现问题，之前安装卸载过 `1.22.0` 版本。

此次安装命令：

```
sealos init --passwd '123456' \
    --master 111.22.33.44 \
    --node 111.22.33.45 \
    --node 111.22.33.46 \
    --pkg-url /root/kube1.19.12.tar.gz \
    --version v1.19.12
```

机器环境

```shell
~ → cat /etc/redhat-release
CentOS Linux release 7.4.1708 (Core)
```

**Comment by zhangguanzhang** [comment]
```
cat -A /root/kubeadm-config.yaml 
```
看下文件所有内容

**Comment by rea1shane** [comment]
内容如下：

```yaml
apiVersion: kubeadm.k8s.io/v1beta1$
kind: InitConfiguration$
localAPIEndpoint:$
  advertiseAddress: 172.16.88.37$
  bindPort: 6443$
nodeRegistration:$
  criSocket: /var/run/dockershim.sock$
---$
apiVersion: kubeadm.k8s.io/v1beta1$
kind: ClusterConfiguration$
kubernetesVersion: v1.19.12$
controlPlaneEndpoint: apiserver.cluster.local:6443$
imageRepository: k8s.gcr.io$
networking:$
  # dnsDomain: cluster.local$
  podSubnet: 100.64.0.0/10$
  serviceSubnet: 10.96.0.0/12$
apiServer:$
  certSANs:$
  - 127.0.0.1$
  - apiserver.cluster.local$
  - 172.16.88.37$
  - 10.103.97.2$
  extraArgs:$
    feature-gates: TTLAfterFinished=true$
  extraVolumes:$
  - name: localtime$
    hostPath: /etc/localtime$
    mountPath: /etc/localtime$
    readOnly: true$
    pathType: File$
controllerManager:$
  extraArgs:$
    feature-gates: TTLAfterFinished=true$
    experimental-cluster-signing-duration: 876000h$
  extraVolumes:$
  - hostPath: /etc/localtime$
    mountPath: /etc/localtime$
    name: localtime$
    readOnly: true$
    pathType: File$
scheduler:$
  extraArgs:$
    feature-gates: TTLAfterFinished=true$
  extraVolumes:$
  - hostPath: /etc/localtime$
    mountPath: /etc/localtime$
    name: localtime$
    readOnly: true$
    pathType: File$
$
---$
apiVersion: kubeproxy.config.k8s.io/v1alpha1$
kind: KubeProxyConfiguration$
mode: ipvs$
ipvs:$
  excludeCIDRs:$
  - 10.103.97.2/32$
$
---$
apiVersion: kubelet.config.k8s.io/v1beta1$
kind: KubeletConfiguration$
authentication:$
  anonymous:$
    enabled: false$
  webhook:$
    cacheTTL: 2m0s$
    enabled: true$
  x509:$
    clientCAFile: /etc/kubernetes/pki/ca.crt$
authorization:$
  mode: Webhook$
  webhook:$
    cacheAuthorizedTTL: 5m0s$
    cacheUnauthorizedTTL: 30s$
cgroupDriver: panic: reflect: indirection through nil pointer to embedded struct [recovered] ^Ipanic: reflect: indirection through nil pointer to embedded struct  goroutine 1 [running]: text/template.errRecover(0xc0005b72e8) ^I/usr/local/go/src/text/template/exec.go:169 +0x1c5 panic(0x56110e388200, 0x56110e681648) ^I/usr/local/go/src/runtime/panic.go:965 +0x1b9 reflect.Value.FieldByIndex(0x56110e51f620, 0xc00012e280, 0x99, 0xc0001e8050, 0x2, 0x2, 0x0, 0x56110e7104c8, 0x56110e388200) ^I/usr/local/go/src/reflect/value.go:889 +0x325 text/template.(*state).evalField(0xc0005b7258, 0x56110e51f620, 0xc00012e280, 0x99, 0x7fff89493605, 0xc, 0x56110e6fa080, 0xc0004b0fc0, 0xc0004080b0, 0x1, ...) ^I/usr/local/go/src/text/template/exec.go:617 +0x4ed text/template.(*state).evalFieldChain(0xc0005b7258, 0x56110e51f620, 0xc00012e280, 0x99, 0x56110e51f620, 0xc00012e280, 0x99, 0x56110e6fa080, 0xc0004b0fc0, 0xc000408080, ...) ^I/usr/local/go/src/text/template/exec.go:570 +0x225 text/template.(*state).evalFieldNode(0xc0005b7258, 0x56110e51f620, 0xc00012e280, 0x99, 0xc0004b0fc0, 0xc0004080b0, 0x1, 0x1, 0x56110e4162a0, 0x56110f494bb0, ...) ^I/usr/local/go/src/text/template/exec.go:534 +0x115 text/template.(*state).evalCommand(0xc0005b7258, 0x56110e51f620, 0xc00012e280, 0x99, 0xc0004b0f60, 0x56110e4162a0, 0x56110f494bb0, 0x99, 0xd0, 0xd0, ...) ^I/usr/local/go/src/text/template/exec.go:462 +0x8f0 text/template.(*state).evalPipeline(0xc0005b7258, 0x56110e51f620, 0xc00012e280, 0x99, 0xc00029a060, 0xc000516498, 0x0, 0xc0005b7160) ^I/usr/local/go/src/text/template/exec.go:436 +0x125 text/template.(*state).walk(0xc0005b7258, 0x56110e51f620, 0xc00012e280, 0x99, 0x56110e6f9e88, 0xc0004b0ff0) ^I/usr/local/go/src/text/template/exec.go:255 +0x38a text/template.(*state).walk(0xc0005b7258, 0x56110e51f620, 0xc00012e280, 0x99, 0x56110e6fa158, 0xc0004b0e40) ^I/usr/local/go/src/text/template/exec.go:264 +0x13c text/template.(*Template).execute(0xc00012e200, 0x56110e6a0b78, 0xc00037b740, 0x56110e51f620, 0xc00012e280, 0x0, 0x0) ^I/usr/local/go/src/text/template/exec.go:220 +0x1c6 text/template.(*Template).Execute(...) ^I/usr/local/go/src/text/template/exec.go:203 github.com/docker/cli/cli/command/system.formatInfo(0x56110e70d2c8, 0xc000114340, 0x0, 0xc00065d320, 0x1, 0x1, 0xc00013a5a0, 0x0, 0x0, 0x0, ...) ^I/go/src/github.com/docker/cli/cli/command/system/info.go:487 +0x1fd github.com/docker/cli/cli/command/system.runInfo(0xc00050c000, 0x56110e70d2c8, 0xc000114340, 0xc00065cbf0, 0x0, 0x0) ^I/go/src/github.com/docker/cli/cli/command/system/info.go:87 +0x3a5 github.com/docker/cli/cli/command/system.NewInfoCommand.func1(0xc00050c000, 0xc000529280, 0x0, 0x2, 0x0, 0x0) ^I/go/src/github.com/docker/cli/cli/command/system/info.go:53 +0x48 github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).execute(0xc00050c000, 0xc0004494b0, 0x2, 0x2, 0xc00050c000, 0xc0004494b0) ^I/go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:850 +0x472 github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc00050c840, 0xc0004494a0, 0x3, 0x3) ^I/go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:958 +0x375 github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).Execute(...) ^I/go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:895 main.runDocker(0xc000114340, 0x56110e6a3118, 0xc00012a010) ^I/go/src/github.com/docker/cli/cmd/docker/docker.go:287 +0x1eb main.main() ^I/go/src/github.com/docker/cli/cmd/docker/docker.go:298 +0xfc$
cgroupsPerQOS: true$
clusterDomain: cluster.local$
configMapAndSecretChangeDetectionStrategy: Watch$
containerLogMaxFiles: 5$
containerLogMaxSize: 10Mi$
contentType: application/vnd.kubernetes.protobuf$
cpuCFSQuota: true$
cpuCFSQuotaPeriod: 100ms$
cpuManagerPolicy: none$
cpuManagerReconcilePeriod: 10s$
enableControllerAttachDetach: true$
enableDebuggingHandlers: true$
enforceNodeAllocatable:$
- pods$
eventBurst: 10$
eventRecordQPS: 5$
evictionHard:$
  imagefs.available: 15%$
  memory.available: 100Mi$
  nodefs.available: 10%$
  nodefs.inodesFree: 5%$
evictionPressureTransitionPeriod: 5m0s$
failSwapOn: true$
fileCheckFrequency: 20s$
hairpinMode: promiscuous-bridge$
healthzBindAddress: 127.0.0.1$
healthzPort: 10248$
httpCheckFrequency: 20s$
imageGCHighThresholdPercent: 85$
imageGCLowThresholdPercent: 80$
imageMinimumGCAge: 2m0s$
iptablesDropBit: 15$
iptablesMasqueradeBit: 14$
kubeAPIBurst: 10$
kubeAPIQPS: 5$
makeIPTablesUtilChains: true$
maxOpenFiles: 1000000$
maxPods: 110$
nodeLeaseDurationSeconds: 40$
nodeStatusReportFrequency: 10s$
nodeStatusUpdateFrequency: 10s$
oomScoreAdj: -999$
podPidsLimit: -1$
port: 10250$
registryBurst: 10$
registryPullQPS: 5$
rotateCertificates: true$
runtimeRequestTimeout: 2m0s$
serializeImagePulls: true$
staticPodPath: /etc/kubernetes/manifests$
streamingConnectionIdleTimeout: 4h0m0s$
syncFrequency: 1m0s$
volumeStatsAggPeriod: 1m0s$
```
