### ISSUE TITLE
sealos4.0 设计

### ISSUE THREAD

**Issue by cuisongliu** [fanux/sealos#885]
```
apiVersion: apps.sealyun.com/v1
kind: Cluster
metadata:
  annotations:
    cluster_DNSDomain: cluster.local
    cluster_apiServerDomain: apiserver.cluster.local
    cluster_certSANS: "127.0.0.1,apiserver.cluster.local,10.103.97.2,192.168.64.15"
    cluster_podCIDR: 100.64.0.0/10
    cluster_serviceCIDR: 10.96.0.0/12
    cluster_vip: 10.103.97.2
  creationTimestamp: null
  name: default
spec:
  env:
  - Interface=eth.*|en.*|em.*
  - IPIP=Always
  - MTU=1440
  - criData=/var/lib/containerd
  - registryData=/var/lib/registry
  - registryConfig=/etc/registry
  - registryDomain=sealos.hub
  - registryPort=5000
  - registryUsername=admin
  - registryPassword=passw0rd
  hosts:
  - ips:
    - 192.168.64.15
    roles:
    - master
    - amd64
  ssh:
    pk: /Users/cuisongliu/.ssh/id_rsa
    port: 22
    user: root

---
apiVersion: apps.sealyun.com/v1
kind: Config
metadata:
  creationTimestamp: null
  name: registry
spec:
  data: |
    domain: sealos.hub
    ip: 192.168.64.15
    password: passw0rd
    port: 5000
    username: admin
  path: etc/registry.yml
  strategy: merge

---
apiVersion: apps.sealyun.com/v1
kind: Config
metadata:
  creationTimestamp: null
  name: registry_passwd
spec:
  data: admin:$2a$10$CtU7HsdWQF.Cmv2UP/5wUuk9viE8HcVFc0Gyh.7JWCfbyPRv5xzTm
  path: etc/registry_htpasswd
  strategy: override

---
apiVersion: apps.sealyun.com/v1
kind: Resource
metadata:
  creationTimestamp: null
  name: sealctl
spec:
  override: opt/sealctl
  path: /Users/cuisongliu/Workspaces/go/src/github.com/fanux/sealos/dist/sealctl_linux_amd64/sealctl
  type: file/binary
status:
  arch: amd64
  metadata: null
  path: /var/lib/sealos/resource/3b7a3a3795af6002a38e03b1650d6e59
  rawPath: /var/lib/sealos/resource/3b7a3a3795af6002a38e03b1650d6e59
  version: v0.0.0-master

---
apiVersion: apps.sealyun.com/v1
kind: Resource
metadata:
  creationTimestamp: null
  name: kube
spec:
  path: /Users/cuisongliu/Workspaces/sealos4.0/bin/kube1.22.0-amd64.tar.gz
  type: kubernetes/tar.gz
status:
  arch: amd64
  data:
    auth: auth.sh
    check: check.sh
    clean: clean.sh $criData
    clean-registry: clean-registry.sh $registryData $registryConfig
    init: init.sh $criData $registryDomain $registryPort $registryUsername $registryPassword
    init-registry: init-registry.sh $registryPort $registryData $registryConfig
  metadata:
    CNIType: calico
    LvscareImage: ghcr.io/sealyun/lvscare:v1.1.3-beta.2
  path: /var/lib/sealos/resource/a73f0f8b3a485d32bf062eaa4d881b82
  rawPath: /var/lib/sealos/resource/sha256:29490abb48c65e824ebc9cdee908e92b15c3e916a3bbcbc1f104af3114a1b5bf
  version: v1.22.0
```

1. 复用了sealer的clusterfile和config
2. 引入新的资源resource，主要解决离线包的问题（1. 离线包本地存储，2. 二进制可以覆盖, 3. 包含一些资源的元信息和执行脚本）
3.  https://github.com/fanux/sealos/issues/883  引入image-shim的feature
4. https://github.com/fanux/sealos/blob/release-v4.0.0/cmd/sealctl/cmd/token.go  解决了token解析问题
5. kubeadm使用 https://github.com/fanux/sealos/tree/release-v4.0.0/pkg/kustomize 进行patch逻辑
6. sealctl 支持写hosts,static-pod ,hostname 等逻辑拆分
